name: r-environment
channels:
  - conda-forge

dependencies:
  - r-base=4.3.1
  - r-ggplot2=3.5.1
  - r-dplyr=1.1.4
  - r-car=3.1-3
  - r-corrplot=0.92
  - r-tidyr=1.3.0
  - r-cowplot=1.1.1
  - r-caret=6.0-94
  - r-docopt=0.7.1
