name: r-environment
channels:
  - conda-forge

dependencies:
  - r-base=4.1.3
  - r-ggplot2=3.5.1
  - r-dplyr=1.1.4
  - r-car=3.1.0
  - r-corrplot=0.92
  - r-tidyr=1.2.1
  - r-cowplot=1.1.1
