name: Run R tests on main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("testthat")
          install.packages("ggplot2")
          install.packages("dplyr")
          install.packages("purrr")
          install.packages("cowplot")

      - name: Run testthat tests
        run: |
          testthat::test_dir("test/testthat")
        shell: Rscript {0}
