name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required packages
        run: |
          install.packages("testthat")
          install.packages("ggplot2")
          install.packages("cowplot")
          install.packages("purrr")
          install.packages("dplyr")

      - name: Source R scripts and run tests
        run: |
          R_files <- list.files("R", full.names = TRUE)
          sapply(R_files, source)
          testthat::test_dir("test/testthat")


