name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Set up job
        run: echo "Starting R test job..."

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("testthat", "tidyverse", "dplyr", "ggplot2", "cowplot", "purrr"))'

      - name: Source R scripts and run tests
        run: |
          Rscript -e 'testthat::test_dir("test/testthat")'
